# .github/workflows/docker-build.yml
name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'services/go/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        service: [billing-service, realtime-service, gateway-service]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: services/go/${{ matrix.service }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pitaia-${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/pitaia-${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max